---
- hosts: all
  become: 'yes'
  become_method: sudo
  gather_facts: 'no'

  pre_tasks:
    - name: ansible needs python2 and aptitude
      raw: sudo apt-get -y install python-simplejson aptitude
    - name: update apt_cache
      apt: update_cache=yes cache_valid_time=6000
    - name: upgrade
      apt: upgrade=safe

  import_tasks:
    - docnow/python_build.yml
    - docnow/other_software.yml
    - docnow/user_setup.yml
    - docnow/virtenv_setup.yml
    - docnow/redis_software.yml
    - docnow/nginx_software.yml
    - docnow/launch_app.yml
