---
- hosts: dnflow-test
  become: yes
  become_method: sudo
  gather_facts: no

  pre_tasks:
    - name: ansible needs python2 and aptitude
      raw: sudo apt-get -y install python-simplejson aptitude
    - name: update apt_cache
      apt: update_cache=yes cache_valid_time=6000
    - name: upgrade
      apt: upgrade=safe

  tasks:
    - include: docnow/python_build.yml
    - include: docnow/other_software.yml
    - include: docnow/user_setup.yml
    - include: docnow/virtenv_setup.yml
    - include: docnow/redis_software.yml
    - include: docnow/nginx_software.yml
    - include: docnow/launch_app.yml
